name: check
on: [push]

jobs:

  job_test0:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
            echo "101010101010101010"


  conditional_jobs_check_files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
      docs_changed2: ${{ steps.check_file_changed.outputs.docs_changed2 }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match 'test1.txt$' }
        $SourceDiff2 = $diff | Where-Object { $_ -match 'test2.txt$' }
        $HasDiff = $SourceDiff.Length -gt 0
        $HasDiff2 = $SourceDiff2.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"
        Write-Host "::set-output name=docs_changed2::$HasDiff2"


  conditional_job_test1:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed == 'true'
    steps:
      - shell: pwsh
        run: |
            echo "111111111"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed}"

  conditional_job_test2:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files, conditional_job_test1 ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed2 == 'true' || (needs.conditional_jobs_check_files.outputs.docs_changed == 'true' && needs.conditional_jobs_check_files.outputs.docs_changed2 == 'true' && success('conditional_job_test1'))
    steps:
      - shell: pwsh
        run: |
            echo "22222222222"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed2}"

  job_test3:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
            echo "333333333"

  job_test4:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
            echo "4444444444"

