name: check
on: [push]

jobs:
  conditional_jobs_check_files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        SourceDiff=$(git diff --name-only HEAD~1 HEAD | grep -E '^src/' | grep -E 'test1.txt$')
        HashDiff=""
        if [ -n "$SourceDiff" ]; then
          HashDiff=true
        else
          HashDiff=false
        fi
        echo "::set-output name=docs_changed::$HashDiff"

  conditional_job_true:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed == 'true'
    steps:
      - shell: pwsh
        run: |
            echo "text file changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed}"


  conditional_job_false:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed == 'false'
    steps:
      - shell: pwsh
        run: |
            echo "text file not changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed}"

