name: check
on: [push]

jobs:
  conditional_jobs_check_files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed1: ${{ steps.check_file_changed.outputs.docs_changed1 }}
      docs_changed2: ${{ steps.check_file_changed.outputs.docs_changed2 }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: powershell
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff1 = $diff | Where-Object { $_ -match '^src/' -or $_ -match 'test1.txt$' }
        $SourceDiff2 = $diff | Where-Object { $_ -match '^src/' -or $_ -match 'test2.txt$' }
        $HasDiff1 = $SourceDiff1.Length -gt 0
        $HasDiff2 = $SourceDiff2.Length -gt 0

        # Set the output named "docs_changed"
        Write-Output "::set-output name=docs_changed1::$HasDiff1"
        Write-Output "::set-output name=docs_changed2::$HasDiff2"


  conditional_job_test1:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed1 == true
    steps:
      - shell: powershell
        run: |
            echo "text file changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed1}"


  conditional_job_test2:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed2 == true
    steps:
      - shell: powershell
        run: |
            echo "text file not changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed2}"

