name: check
on: [push]

jobs:
  conditional_jobs_check_files:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^src/' -or $_ -match 'test1.txt$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

  conditional_job_true:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed == 'true'
    steps:
      - shell: pwsh
        run: |
            echo "text file changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed}"


  conditional_job_false:
    runs-on: ubuntu-latest
    needs: [ conditional_jobs_check_files ]
    if: needs.conditional_jobs_check_files.outputs.docs_changed == 'false'
    steps:
      - shell: pwsh
        run: |
            echo "text file not changed"
            echo "${needs.conditional_jobs_check_files.outputs.docs_changed}"

