name: test hotfix

on:
  push:
    branches:
      - main

jobs:
  test-hotfix:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Check for "hotfix" in commit message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"hotfix"* ]]; then
            echo "Commit message contains 'hotfix'. Notify via Slack."
            echo "status=success" >> $GITHUB_ENV  # Set the environment variable
          else
            echo "No action needed."
            echo "status=fail" >> $GITHUB_ENV  # Set the environment variable
          fi

      - name: Echo message
        run: |
          if [[ $status == "success" ]]; then
            echo "should be printed"
          else
            echo "Dont notify"
            exit 0  # Exit with a non-zero code to indicate an error
          fi
