name: test hotfix

on:
  push:
    branches:
      - main-v2

jobs:
  test-hotfix:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check for "hotfix" in commit message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"hotfix"* ]]; then
            echo "Commit message contains 'hotfix'. Moving to the next step..."
          else
            echo "No action needed. Commit message does not contain 'hotfix'. Exiting job."
            exit 0
          fi

      - name: Echo message
        run: |
          echo "yes"
